# Python from Course 5 Task 1 Step 2

Libraries or Modules

In [45]:
from numpy import random

In [46]:
import numpy as np

In [47]:
import  math
math.sqrt(25)

5.0

In [48]:
math.pi


3.141592653589793

In [51]:
# uniform random numbers in [0,1]
dataOne = random.rand(5,5)
print(dataOne)

[[0.0580912  0.84260115 0.16503391 0.49610068 0.17861747]
 [0.05241048 0.76265009 0.21590821 0.69341686 0.03813606]
 [0.1185308  0.07436023 0.77451481 0.79826983 0.44905082]
 [0.05540061 0.2656215  0.42901642 0.39027805 0.0153117 ]
 [0.04839619 0.0692491  0.21856085 0.40388588 0.45704249]]


In [16]:
np.mean(dataOne)

0.3918087688895937

In [20]:
import scipy.stats as sts

In [22]:
sts.pi

AttributeError: module 'scipy.stats' has no attribute 'pi'

Functions

In [23]:
functionName()

NameError: name 'functionName' is not defined

In [24]:
print('I Love data Science')



I Love data Science


Variables

In [25]:
variableName = 25

In [26]:
variableName1 = 'I Love data Science'

In [27]:
print(variableName1)

I Love data Science


Data Types

In [28]:
variableName = 25

In [29]:
type(variableName)

int

In [30]:
variableName = 25.0

In [31]:
type(variableName)

float

In [32]:
varOne = 25

In [33]:
varTwo = 25.0

In [34]:
varThree = varOne + varTwo

In [35]:
print(varThree)

50.0


In [36]:
varOne = 25

In [37]:
varTwo = 'Hello'

In [38]:
varThree = varOne + varTwo

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [39]:
print(varThree)

50.0


Lists and Dictionaries

In [40]:
listName = [ ]

In [41]:
listOne = [1,2,3,4]

In [42]:
print(listOne[1:3])

[2, 3]


Dictionaries

In [43]:
tel = {'jack': 4098, 'sape': 4139}

In [44]:
tel['jack']

4098

Define a variable that represents a dictionary with 5 INT elements

In [52]:
var = {'dog': 5,'cat': 6,'fish': 7,'giraffe': 8, 'bird': 9}

In [53]:
var['dog']

5

In [55]:
varthree = var['dog']+ var['cat']
print (varthree)

11


# Python for Dummies 

Chapter 4

Page 79 

In [1]:
ord("A") 

65

In [2]:
myInt = int("123") 

In [3]:
print(myInt)

123


Page 81

In [8]:
import datetime

In [9]:
datetime.datetime. now()

datetime.datetime(2018, 8, 6, 20, 7, 37, 141484)

In [10]:
str(datetime.datetime.now().date())

'2018-08-06'

Page 83

In [16]:
def SayHello():
    print('Hello There!')

In [17]:
SayHello()

Hello There!


Page 84

In [18]:
def DoSum(Value1, Value2): 
    return Value1 + Value2

In [19]:
DoSum(1,2)

3

In [22]:
def DisplaySum(Value1, Value2):print(str(Value1) + ' + ' + str(Value2) + ' = ' + str((Value1 + Value2)))

In [23]:
DisplaySum(1,2)

1 + 2 = 3


In [24]:
DisplaySum(Value2 = 2, Value1 = 1)

1 + 2 = 3


Page 86

In [25]:
def SayHello(Greeting = "No Value Supplied"): print(Greeting)

In [26]:
SayHello()

No Value Supplied


In [27]:
SayHello('Howdy!')

Howdy!


In [36]:
def DisplayMulti(ArgCount = 0, *VarArgs):
    print('You passed ' + str(ArgCount) + ' arguments.', VarArgs)

In [37]:
DisplayMulti( )

You passed 0 arguments. ()


In [38]:
DisplayMulti(3, 'Hello', 1, True)

You passed 3 arguments. ('Hello', 1, True)


In [ ]:
Page 87

In [48]:
def TestValue(Value): 
    if Value == 5:
        print('Value equals 5!') 
    elif Value == 6:
        print('Value equals 6!') 
    else:
        print('Value is something else.') 
        print('It equals ' + str(Value))


In [52]:
TestValue(8)
TestValue(1)
TestValue(5)

Value is something else.
It equals 8
Value is something else.
It equals 1
Value equals 5!


Page 88

In [65]:
def SecretNumber():
    One = int(input("Type a number between 1 and 10: ")) 
    Two = int(input("Type a number between 1 and 10: "))

if (One >= 1) and (One <= 10):
    if (Two >= 1) and (Two <= 10):
        print('Your secret number is: ' + str(One * Two)) 
    else:
        print("Incorrect second value!") 
else:
    print("Incorrect first value!")

NameError: name 'One' is not defined

In [67]:
 SecretNumber()

Type a number between 1 and 10: 10
Type a number between 1 and 10: 10


Page 89

In [68]:
def DisplayMulti(*VarArgs): 
    for Arg in VarArgs:
        if Arg.upper() == 'CONT': 
            continue
            print('Continue Argument: ' + Arg) 
        elif Arg.upper() == 'BREAK':
            break
            print('Break Argument: ' + Arg) 
        print('Good Argument: ' + Arg)

In [69]:
DisplayMulti('Hello', 'Goodbye', 'First', 'Last')

Good Argument: Hello
Good Argument: Goodbye
Good Argument: First
Good Argument: Last


In [70]:
DisplayMulti('Hello', 'Cont', 'Goodbye', 'Break', 'Last') 

Good Argument: Hello
Good Argument: Goodbye


Page 90

In [71]:
def SecretNumber(): 
    GotIt = False
    while GotIt == False:
        One = int(input("Type a number between 1 and 10: ")) 
        Two = int(input("Type a number between 1 and 10: "))
        
        if (One >= 1) and (One <= 10):
            if (Two >= 1) and (Two <= 10):
                print('Secret number is: ' + str(One * Two)) 
                GotIt = True
                continue
            else:
                print("Incorrect second value!") 
        else:
            print("Incorrect first value!") 
        print("Try again!")

In [72]:
SecretNumber()

Type a number between 1 and 10: 20
Type a number between 1 and 10: 10
Incorrect first value!
Try again!
Type a number between 1 and 10: 5
Type a number between 1 and 10: 1
Secret number is: 5


Page 91

In [80]:
from sets import Set
SetA = Set(['Red', 'Blue', 'Green', 'Black'])
SetB = Set(['Black', 'Green', 'Yellow', 'Orange']) 
SetX = SetA.union(SetB)
SetY = SetA.intersection(SetB)
SetZ = SetA.difference(SetB)

ModuleNotFoundError: No module named 'sets'

In [81]:
print {0}\n{1}\n{2}.format(SetX, SetY, SetZ)
Set(['Blue', 'Yellow', 'Green', 'Orange', 'Black', 'Red']) 
Set(['Green', 'Black'])
Set(['Blue', 'Red'])

SyntaxError: invalid syntax (<ipython-input-81-c27887bacfda>, line 1)

In [82]:
Set(['Blue', 'Yellow', 'Green', 'Orange', 'Black', 'Red']) 
Set(['Green', 'Black'])
Set(['Blue', 'Red'])

NameError: name 'Set' is not defined

In [83]:
SetA.issuperset(SetY)

NameError: name 'SetA' is not defined

Page 93

In [84]:
ListA = [0, 1, 2, 3] 
ListB = [4, 5, 6, 7] 
ListA.extend(ListB) 
ListA

[0, 1, 2, 3, 4, 5, 6, 7]

In [93]:
ListA.append(-5) 

In [94]:
ListA

[0, 1, 2, 3, 4, 5, 6, 7, 5, -5]

In [95]:
ListA.remove(-5)

In [96]:
ListX = ListA + ListB

Page 94

In [97]:
MyTuple = (1, 2, 3, (4, 5, 6, (7, 8, 9)))

In [104]:
for Value1 in MyTuple:
    if type(Value1) == int:
        print (Value1)
    else:
        for Value2 in Value1:
            if type(Value2) == int:
                print ("\t", Value2) 
        else:
            for Value3 in Value2: 
                print ("\t\t", Value3)

1
2
3
	 4
	 5
	 6
		 7
		 8
		 9


In [105]:
MyNewTuple = MyTuple.__add__((10, 11, 12, (13, 14, 15)))

In [106]:
MyNewTuple()

TypeError: 'tuple' object is not callable

In [107]:
ListA = ['Orange', 'Yellow', 'Green', 'Brown'] 
ListB = [1, 2, 3, 4]

In [108]:
ListA[1]

'Yellow'

In [110]:
for Value in ListB[1:3]: 
    print (Value)

2
3


Page 96

In [111]:
for Value1, Value2 in zip(ListA, ListB): 
    print (Value1, '\t', Value2)

Orange 	 1
Yellow 	 2
Green 	 3
Brown 	 4


In [112]:
MyDict = {'Orange':1, 'Blue':2, 'Pink':3} 

In [113]:
MyDict['Pink']

3

In [114]:
MyDict.keys( )

dict_keys(['Orange', 'Blue', 'Pink'])