# Python from Course 5 Task 1 Step 2

Libraries or Modules

In [45]:
from numpy import random

In [46]:
import numpy as np

In [47]:
import  math
math.sqrt(25)

5.0

In [48]:
math.pi


3.141592653589793

In [51]:
# uniform random numbers in [0,1]
dataOne = random.rand(5,5)
print(dataOne)

[[0.0580912  0.84260115 0.16503391 0.49610068 0.17861747]
 [0.05241048 0.76265009 0.21590821 0.69341686 0.03813606]
 [0.1185308  0.07436023 0.77451481 0.79826983 0.44905082]
 [0.05540061 0.2656215  0.42901642 0.39027805 0.0153117 ]
 [0.04839619 0.0692491  0.21856085 0.40388588 0.45704249]]


In [16]:
np.mean(dataOne)

0.3918087688895937

In [20]:
import scipy.stats as sts

In [22]:
sts.pi

AttributeError: module 'scipy.stats' has no attribute 'pi'

Functions

In [23]:
functionName()

NameError: name 'functionName' is not defined

In [24]:
print('I Love data Science')



I Love data Science


Variables

In [25]:
variableName = 25

In [26]:
variableName1 = 'I Love data Science'

In [27]:
print(variableName1)

I Love data Science


Data Types

In [28]:
variableName = 25

In [29]:
type(variableName)

int

In [30]:
variableName = 25.0

In [31]:
type(variableName)

float

In [32]:
varOne = 25

In [33]:
varTwo = 25.0

In [34]:
varThree = varOne + varTwo

In [35]:
print(varThree)

50.0


In [36]:
varOne = 25

In [37]:
varTwo = 'Hello'

In [38]:
varThree = varOne + varTwo

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [39]:
print(varThree)

50.0


Lists and Dictionaries

In [40]:
listName = [ ]

In [41]:
listOne = [1,2,3,4]

In [42]:
print(listOne[1:3])

[2, 3]


Dictionaries

In [43]:
tel = {'jack': 4098, 'sape': 4139}

In [44]:
tel['jack']

4098

Define a variable that represents a dictionary with 5 INT elements

In [52]:
var = {'dog': 5,'cat': 6,'fish': 7,'giraffe': 8, 'bird': 9}

In [53]:
var['dog']

5

In [55]:
varthree = var['dog']+ var['cat']
print (varthree)

11
